name: flexit-api-ci
on: push

jobs:
  pytest:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.10.2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest -v tests/
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
